In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
import statsmodels.formula.api as smf
from sklearn.ensemble import RandomForestRegressor
%matplotlib inline
sns.set(style="whitegrid")

In [ ]:
df=pd.read_csv("marketing_campaign_dataset.csv")

In [ ]:
df.shape

(200000, 16)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Campaign_ID       200000 non-null  int64
 1   Company           200000 non-null  object
 2   Campaign_Type     200000 non-null  object
 3   Target_Audience   200000 non-null  object
 4   Duration          200000 non-null  object
 5   Channel_Used      200000 non-null  object
 6   Conversion_Rate   200000 non-null  float64
 7   Acquisition_Cost  200000 non-null  object
 8   ROI               200000 non-null  float64
 9   Location          200000 non-null  object
 10  Language          200000 non-null  object
 11  Clicks            200000 non-null  int64
 12  Impressions       200000 non-null  int64
 13  Engagement_Score  200000 non-null  int64
 14  Customer_Segment  200000 non-null  object
 15  Date              200000 non-null  object
dtypes: float64(2), int64(4), object(10)
memory usage: 24.4+ MB

In [ ]:
df.isnull().sum()

Campaign_ID         0
Company             0
Campaign_Type       0
Target_Audience     0
Duration            0
Channel_Used        0
Conversion_Rate     0
Acquisition_Cost    0
ROI                 0
Location            0
Language            0
Clicks              0
Impressions         0
Engagement_Score    0
Customer_Segment    0
Date                0
dtype: int64

In [ ]:
df.head()

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Language,Clicks,Impressions,Engagement_Score,Customer_Segment,Date
0,1,Innovate Industries,Email,Men 18-24,30 days,Google Ads,0.04,"$16,174.00",6.29,Chicago,Spanish,506,1922,6,Health & Wellness,2021-01-01
1,2,NexGen Systems,Email,Women 35-44,60 days,Google Ads,0.12,"$11,566.00",5.61,New York,German,116,7523,7,Fashionistas,2021-01-02
2,3,Alpha Innovations,Influencer,Men 25-34,30 days,YouTube,0.07,"$10,200.00",7.18,Los Angeles,French,584,7698,1,Outdoor Adventurers,2021-01-03
3,4,DataTech Solutions,Display,All Ages,60 days,YouTube,0.11,"$12,724.00",5.55,Miami,Mandarin,217,1820,7,Health & Wellness,2021-01-04
4,5,NexGen Systems,Email,Men 25-34,15 days,YouTube,0.05,"$16,452.00",6.50,Los Angeles,Mandarin,379,4201,3,Health & Wellness,2021-01-05

In [ ]:
df.tail()

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Language,Clicks,Impressions,Engagement_Score,Customer_Segment,Date
199995,199996,TechCorp,Display,All Ages,30 days,Google Ads,0.06,"$18,365.00",2.84,Chicago,German,858,5988,1,Tech Enthusiasts,2021-12-07
199996,199997,DataTech Solutions,Email,Men 25-34,15 days,Facebook,0.02,"$8,168.00",4.14,Chicago,Spanish,228,3068,7,Foodies,2021-12-08
199997,199998,DataTech Solutions,Social Media,Men 18-24,45 days,Website,0.05,"$13,397.00",3.25,New York,Mandarin,723,9548,3,Tech Enthusiasts,2021-12-09
199998,199999,Innovate Industries,Influencer,All Ages,30 days,YouTube,0.10,"$18,508.00",3.86,Houston,French,528,2763,1,Foodies,2021-12-10
199999,200000,Innovate Industries,Social Media,Women 35-44,45 days,Google Ads,0.01,"$13,835.00",6.64,Chicago,Spanish,924,7287,8,Tech Enthusiasts,2021-12-11

In [ ]:
df['Customer_Segment'].value_counts()

Customer_Segment
Foodies                40208
Tech Enthusiasts       40151
Outdoor Adventurers    40011
Health & Wellness      39888
Fashionistas           39742
Name: count, dtype: int64

In [ ]:
df['Language'].value_counts()

Language
Mandarin    40255
Spanish     40102
German      39983
English     39896
French      39764
Name: count, dtype: int64

In [ ]:
df['Target_Audience'].value_counts()

Target_Audience
Men 18-24      40258
Men 25-34      40023
All Ages       40019
Women 25-34    40013
Women 35-44    39687
Name: count, dtype: int64

In [ ]:
df['Duration'].value_counts()

Duration
30 days    50255
45 days    50100
60 days    49866
15 days    49779
Name: count, dtype: int64

In [ ]:
df.drop(["Campaign_ID","Company"],axis =1)

,Campaign_Type,Target_Audience,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Language,Clicks,Impressions,Engagement_Score,Customer_Segment,Date
0,Email,Men 18-24,30 days,Google Ads,0.04,"$16,174.00",6.29,Chicago,Spanish,506,1922,6,Health & Wellness,2021-01-01
1,Email,Women 35-44,60 days,Google Ads,0.12,"$11,566.00",5.61,New York,German,116,7523,7,Fashionistas,2021-01-02
2,Influencer,Men 25-34,30 days,YouTube,0.07,"$10,200.00",7.18,Los Angeles,French,584,7698,1,Outdoor Adventurers,2021-01-03
3,Display,All Ages,60 days,YouTube,0.11,"$12,724.00",5.55,Miami,Mandarin,217,1820,7,Health & Wellness,2021-01-04
4,Email,Men 25-34,15 days,YouTube,0.05,"$16,452.00",6.50,Los Angeles,Mandarin,379,4201,3,Health & Wellness,2021-01-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,Display,All Ages,30 days,Google Ads,0.06,"$18,365.00",2.84,Chicago,German,858,5988,1,Tech Enthusiasts,2021-12-07
199996,Email,Men 25-34,15 days,Facebook,0.02,"$8,168.00",4.14,Chicago,Spanish,228,3068,7,Foodies,2021-12-08
199997,Social Media,Men 18-24,45 days,Website,0.05,"$13,397.00",3.25,New York,Mandarin,723,9548,3,Tech Enthusiasts,2021-12-09
199998,Influencer,All Ages,30 days,YouTube,0.10,"$18,508.00",3.86,Houston,French,528,2763,1,Foodies,2021-12-10
199999,Social Media,Women 35-44,45 days,Google Ads,0.01,"$13,835.00",6.64,Chicago,Spanish,924,7287,8,Tech Enthusiasts,2021-12-11

In [ ]:
df['Acquisition_Cost'] = df['Acquisition_Cost'].str.replace('$', '', regex=False).str.replace(',', '', regex=False).astype(float)

categorical_cols = df.select_dtypes(include='object').columns.tolist()
categorical_cols.remove('Date') # Assuming 'Date' won't be one-hot encoded but might need different processing

df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

print("Original DataFrame shape:", df.shape)
print("Encoded DataFrame shape:", df.shape)
print("First 5 rows of the encoded DataFrame:")
print(df.head())

Original DataFrame shape: (200000, 40)
Encoded DataFrame shape: (200000, 40)
First 5 rows of the encoded DataFrame:
   Campaign_ID  Conversion_Rate  Acquisition_Cost   ROI  Clicks  Impressions  \
0            1             0.04           16174.0  6.29     506         1922
1            2             0.12           11566.0  5.61     116         7523
2            3             0.07           10200.0  7.18     584         7698
3            4             0.11           12724.0  5.55     217         1820
4            5             0.05           16452.0  6.50     379         4201

   Engagement_Score        Date  Company_DataTech Solutions  \
0                 6  2021-01-01                       False
1                 7  2021-01-02                       False
2                 1  2021-01-03                       False
3                 7  2021-01-04                        True
4                 3  2021-01-05                       False

   Company_Innovate Industries  ...  Location_Miami  Location_New York  \
0                         True  ...           False              False
1                        False  ...           False               True
2                        False  ...           False              False
3                        False  ...            True              False
4                        False  ...           False              False

   Language_French  Language_German  Language_Mandarin  Language_Spanish  \
0            False            False              False              True
1            False             True              False             False
2             True            False              False             False
3            False            False               True             False
4            False            False               True             False

   Customer_Segment_Foodies  Customer_Segment_Health & Wellness  \
0                     False                                True
1                     False                               False
2                     False                               False
3                     False                                True
4                     False                                True

   Customer_Segment_Outdoor Adventurers  Customer_Segment_Tech Enthusiasts
0                                 False                              False
1                                 False                              False
2                                  True                              False
3                                 False                              False
4                                 False                              False

[5 rows x 40 columns]

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])

df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
df['DayOfWeek'] = df['Date'].dt.dayofweek
df['DayOfYear'] = df['Date'].dt.dayofyear
df['WeekOfYear'] = df['Date'].dt.isocalendar().week.astype(int)

print("DataFrame with new date features:")
print(df[['Date', 'Year', 'Month', 'Day', 'DayOfWeek', 'DayOfYear', 'WeekOfYear']].head())

DataFrame with new date features:
        Date  Year  Month  Day  DayOfWeek  DayOfYear  WeekOfYear
0 2021-01-01  2021      1    1          4          1          53
1 2021-01-02  2021      1    2          5          2          53
2 2021-01-03  2021      1    3          6          3          53
3 2021-01-04  2021      1    4          0          4           1
4 2021-01-05  2021      1    5          1          5           1

In [ ]:
from sklearn.model_selection import train_test_split

# Define features (X) and target (y)
X = df.drop(['ROI', 'Date', 'Campaign_ID'], axis=1)
y = df['ROI']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (160000, 43)
X_test shape: (40000, 43)
y_train shape: (160000,)
y_test shape: (40000,)

In [ ]:
# Define hypothetical treatment and control groups based on 'Location'
# Assuming 'New York' is the treated location and 'Miami' is the control location for this example
df_causal = df[df['Location_New York'] | df['Location_Miami']].copy()

# Define the treatment group (1 for New York, 0 for Miami)
df_causal['is_treated'] = df_causal['Location_New York'].astype(int)

# Define the campaign start date
campaign_start_date = pd.to_datetime('2021-07-01')

# Define the 'post' period (1 for dates after campaign_start_date, 0 otherwise)
df_causal['post_campaign'] = (df_causal['Date'] >= campaign_start_date).astype(int)

# Create the interaction term for DID
df_causal['treatment_post'] = df_causal['is_treated'] * df_causal['post_campaign']

print("Causal Inference DataFrame head:")
print(df_causal[['Date', 'Location_New York', 'Location_Miami', 'is_treated', 'post_campaign', 'treatment_post', 'ROI']].head())

Causal Inference DataFrame head:
         Date  Location_New York  Location_Miami  is_treated  post_campaign  \
1  2021-01-02               True           False           1              0
3  2021-01-04              False            True           0              0
5  2021-01-06               True           False           1              0
10 2021-01-11               True           False           1              0
13 2021-01-14               True           False           1              0

    treatment_post   ROI
1                0  5.61
3                0  5.55
5                0  4.36
10               0  3.49
13               0  7.06

Now that we have defined our hypothetical treatment and control groups and pre/post periods, the data is ready for the Difference-in-Differences (DID) analysis. This technique will help us estimate the causal effect of the campaign.

In [ ]:
import statsmodels.formula.api as smf

# Perform Difference-in-Differences (DID) analysis
# Formula: ROI ~ is_treated + post_campaign + treatment_post

# Drop rows with NaN values if any, although our data was clean earlier
df_did = df_causal.dropna(subset=['ROI', 'is_treated', 'post_campaign', 'treatment_post'])

did_model = smf.ols("ROI ~ is_treated + post_campaign + treatment_post", data=df_did).fit()

print("Difference-in-Differences Model Summary:")
print(did_model.summary())

Difference-in-Differences Model Summary:
                            OLS Regression Results
==============================================================================
Dep. Variable:                    ROI   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                     2.932
Date:                Sat, 02 May 2026   Prob (F-statistic):             0.0321
Time:                        11:40:19   Log-Likelihood:            -1.5822e+05
No. Observations:               80293   AIC:                         3.164e+05
Df Residuals:                   80289   BIC:                         3.165e+05
Df Model:                           3
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept          5.0081      0.012    408.641      0.000       4.984       5.032
is_treated        -0.0393      0.017     -2.261      0.024      -0.073      -0.005
post_campaign      0.0084      0.017      0.487      0.626      -0.025       0.042
treatment_post     0.0143      0.025      0.584      0.559      -0.034       0.062
==============================================================================
Omnibus:                    75904.701   Durbin-Watson:                   1.997
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             4872.678
Skew:                          -0.003   Prob(JB):                         0.00
Kurtosis:                       1.793   Cond. No.                         6.87
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

The `treatment_post` coefficient in the DID model summary represents the estimated causal effect of the campaign. A positive and statistically significant coefficient suggests a positive impact. We can now visualize this effect and proceed with other causal inference techniques.